stages:
  - build
  - deploy

build:
  stage: build
  tags: 
    - shell
  script:
    - docker build -t m2-frontend udagram-frontend
    - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
    - docker tag m2-frontend $DOCKER_LOWER_USERNAME/m2-frontend:latest
    - docker push $DOCKER_LOWER_USERNAME/m2-frontend:latest
    - docker build -t m2-reverseproxy udagram-reverseproxy
    - docker tag m2-reverseproxy $DOCKER_LOWER_USERNAME/m2-reverseproxy:latest
    - docker push $DOCKER_LOWER_USERNAME/m2-reverseproxy:latest
    - docker build -t m2-backend-feed udagram-api-feed
    - docker tag m2-backend-feed $DOCKER_LOWER_USERNAME/m2-backend-feed:latest
    - docker push $DOCKER_LOWER_USERNAME/m2-backend-feed:latest
    - docker build -t m2-backend-user udagram-api-user
    - docker tag m2-backend-user $DOCKER_LOWER_USERNAME/m2-backend-user:latest
    - docker push $DOCKER_LOWER_USERNAME/m2-backend-user:latest
    

deploy:
  stage: deploy
  tags:
    - shell
  script:
    - docker-compose up --abort-on-container-exit
